name       : kwave
version    : 23.04.3
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kwave-23.04.3.tar.xz : 5d92998c67964305e2e2b38cffb1c8da743b345e292811a5e392d2c59f443c69
homepage   : https://kde.org/applications/multimedia/org.kde.kwave
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A sound editor for KDE
description: |
    With Kwave you can record, play back, import and edit many sorts of audio files including multi channel files. Kwave includes some plugins to transform audio files in several ways and presents a graphical view with a complete zoom- and scroll capability.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(flac)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mad)
    - pkgconfig(opus)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - id3lib-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc

    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/kwave.png
