name       : kwave
version    : 19.12.3
release    : 3
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kwave-19.12.3.tar.xz : 3c90115d4702dbe46767e2404c952d84533137fa558b787b87ff95ed61f6930d
homepage   : https://kde.org/applications/multimedia/org.kde.kwave
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A sound editor for KDE
description: |
    A sound editor for KDE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(flac)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(opus)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - id3lib-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - libmad-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
