name       : kwave
version    : 21.12.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kwave-21.12.1.tar.xz : 85c74147079a3502dc97a4aa37c6513106152a1c6c4c7dacbf01786ac5a18861
homepage   : https://kde.org/applications/multimedia/org.kde.kwave
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A sound editor for KDE
description: |
    A sound editor for KDE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(flac)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(opus)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - id3lib-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - libmad-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
