name       : kwave
version    : 22.04.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kwave-22.04.2.tar.xz : 154c41fb11dad2cb09390c7d203d54ceddfacfcfbdcc972744e3b37e3ba8d74c
homepage   : https://kde.org/applications/multimedia/org.kde.kwave
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A sound editor for KDE
description: |
    A sound editor for KDE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(flac)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(opus)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - id3lib-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - libmad-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
