name       : kwave
version    : 20.04.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kwave-20.04.3.tar.xz : 111ea78c90371f566500e88d746812b17875e154e431b3694e3d226f3f19e988
homepage   : https://kde.org/applications/multimedia/org.kde.kwave
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A sound editor for KDE
description: |
    A sound editor for KDE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(audiofile)
    - pkgconfig(flac)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(opus)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - id3lib-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libmad-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
